# Define a tensor
Yu Jingyao, 1/7/2026

In [2]:
import torch
import numpy as np

标量：数字，1，2，3 (0阶张量)
向量：一串数字，[1,2,3] （1阶张量）
矩阵：一板数字，[[1,2],[3,4],[5,6]] （2阶张量）
张量：任意阶数的数字，如四阶张量（1x2x1x2）[[[[1,2]],[[3,4]]]]

In [3]:
torch.rand((1,2,3,4))

tensor([[[[0.6970, 0.9018, 0.4671, 0.7777],
          [0.6617, 0.8681, 0.9318, 0.1184],
          [0.9016, 0.4495, 0.8986, 0.7982]],

         [[0.0912, 0.6680, 0.1622, 0.1672],
          [0.4173, 0.9472, 0.8173, 0.5145],
          [0.8027, 0.3974, 0.7970, 0.9326]]]])

数据（样本，标签）要使用张量表示，用来训练模型

In [4]:
# 创建张量

# 定义具体内容
a = torch.tensor([[1,2],[3,4]])
np.array([[1,2],[3,4]])
print(a.type())

# 只定义大小，数值从内存中取
a_empty = torch.empty(2,2)
np.empty((2,2)) # 注意
print(a_empty)

torch.LongTensor
tensor([[0., 0.],
        [0., 0.]])


In [5]:
# 定义全0/1张量
b1 = torch.ones(2,3,4)
np.ones((2,3,4)) # 注意
print(b1)

b2 = torch.zeros(2,3,4)
np.zeros((2,3,4))
print(b2)

# 定义全0/1张量，但是采用其他张量的形状
b3 = torch.zeros_like(a)
np.zeros_like(a)
print(b3)

b4 = torch.ones_like(a)
np.ones_like(a)
print(b4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[0, 0],
        [0, 0]])
tensor([[1, 1],
        [1, 1]])


In [6]:
# 定义单位张量
c1 = torch.eye(3,3)
print(c1)

# c2 = torch.eye(3,3,3)  只能是二阶张量
# print(c2)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [7]:
# 定义随机数值张量
d1 = torch.rand(2,3) # rand是默认的【0，1）均匀分布
print(d1)

# 正态分布
d2 = torch.normal(mean=0, std=1, size=(3,3))
d3 = torch.normal(mean=0, std=torch.rand(4)) # 根据四组标准差生成四组正态分布，再从正态分布里面，分别挑出四个随机数
d4 = torch.normal(mean=torch.tensor([2.,3.,4.,5.]), std=torch.ones(4, dtype=float)) # 同理，均值标准差都可以是浮点型张量，但是维度必须一致
print(d2)
print(d3)

# 均匀分布
d5 = torch.empty(2,2).uniform_(-1,1) # uniform后面的下划线表示“原地操作”，它会直接修改原来的张量
d5_rand = 2 * torch.rand(2,2) - 1 # rand是默认的【0，1）均匀分布，只需要乘以范围大小再加上下限即可进行转化

print(d5)
print(d5_rand)

tensor([[0.6154, 0.5562, 0.9404],
        [0.4244, 0.0154, 0.6506]])
tensor([[ 0.9466,  0.3901,  0.1142],
        [-2.0056,  0.1288, -0.5661],
        [-2.1208, -0.9468, -0.2757]])
tensor([ 0.4915, -0.7427, -0.0383, -0.3853])
tensor([[-0.9984,  0.9196],
        [-0.5049,  0.5498]])
tensor([[ 0.7798, -0.8019],
        [ 0.2418, -0.2022]])


In [9]:
# 定义序列张量
e1 = torch.arange(0,11,1) # 与python中的range()性质一致，左闭右开
print(e1)

e2 = torch.linspace(0,12,5) # linear spaced, 等间距分布，注意这里是闭区间 （首项， 末项， 项数）
print(e2)

e3 = torch.randperm(5) # Random Permutation, 生成从0-4的乱序整数张量, 洗牌，无重复
print(e3)

e4 = torch.randint(0, 4, (4,3)) # random integer, 抽奖，会有重复
print(e4)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([ 0.,  3.,  6.,  9., 12.])
tensor([1, 0, 3, 4, 2])
tensor([[1, 0, 3],
        [3, 2, 0],
        [3, 2, 2],
        [2, 2, 2]])
