# Statistics in pytorch
Yu Jingyao, 1/13/2026

In [3]:
import torch
a = torch.rand(2,2,2)

In [ ]:
# 平均值
print(a)
print(torch.mean(a, dim=2))
print(torch.sum(a, dim=1))
print(torch.prod(a, dim=0))

tensor([[[0.5293, 0.6983],
         [0.1902, 0.8746]],

        [[0.9829, 0.6625],
         [0.3479, 0.2625]]])
tensor([[0.6138, 0.5324],
        [0.8227, 0.3052]])
tensor(0.5685)
tensor([[0.7196, 1.5729],
        [1.3308, 0.9250]])
tensor([[0.5203, 0.4626],
        [0.0662, 0.2296]])


In [ ]:
# 最大/小值的索引位置
print(torch.argmax(a, dim=0))
print(torch.argmin(a, dim=0))

tensor([[1, 0],
        [1, 0]])


In [16]:
# 其他
print(torch.std(a))
print(torch.var(a))
print(torch.median(a))
print(torch.mode(a))



tensor(0.2874)
tensor(0.0826)
tensor(0.5293)
torch.return_types.mode(
values=tensor([[0.5293, 0.1902],
        [0.6625, 0.2625]]),
indices=tensor([[0, 0],
        [1, 1]]))


In [18]:
a = torch.rand(2,2,2) * 10
print(torch.histc(a, 6, 0, 0))

tensor([1., 1., 0., 2., 1., 3.])
