# Tensor operations
Yu Jingyao, 1/7/2026

In [2]:
import torch

In [39]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])

In [8]:
# 加法
print(a + b)
print(torch.add(a, b))
print(a.add(b))
# a.add_(b) 原地操作

tensor([[ 6,  8],
        [10, 12]])
tensor([[ 6,  8],
        [10, 12]])
tensor([[ 6,  8],
        [10, 12]])


In [9]:
# 减法
print(a-b)
print(torch.sub(a,b))
print(a.sub(b))
# a.sub_(b)

tensor([[-4, -4],
        [-4, -4]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[-4, -4],
        [-4, -4]])


In [15]:
# 乘法（对应元素直接）
print(a*b)
print(torch.mul(a,b))
print(a.mul(b))
# a.mul_(b)

tensor([[ 5, 12],
        [21, 32]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[ 5, 12],
        [21, 32]])


In [16]:
# 除法（对应元素相除）
print(a / b)
print(torch.div(a,b))
print(a.div(b))
# a.div_(b)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [28]:
# 矩阵乘法
# 二阶矩阵
print(a@b)
print(torch.mm(a,b))
print(a.mm(b))
print(torch.matmul(a,b))
print(a.matmul(b))

# 高阶矩阵（只作用于最后两个维度）
c = torch.ones(2,3,4)
d = torch.ones(4,3)
print(torch.matmul(c,d))


tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor([[[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]])


In [29]:
# 幂运算
print(a**2)
print(torch.pow(a,2))
print(a.pow(2))
print()
# a.pow_(2)

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])



In [30]:
# 开方运算
print(a.sqrt())
# a.sqrt_()

tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])


In [33]:
# 指数运算
print(torch.exp(a))
print(a.exp())
# a.exp_()

# 对数运算
print(torch.log(a)) # 底数为e

tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5981]])
tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5981]])
tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]])


In [48]:
x = torch.rand(2,3) + 3
print(x)

tensor([[3.4009, 3.4505, 3.6772],
        [3.8545, 3.4672, 3.2331]])


In [52]:
# 取整运算
print(torch.floor(x)) # 向下取整
print(x.ceil()) # 向上取整
print(x.round()) # 四舍五入
print(torch.trunc(x)) # 取整数部分
print(torch.frac(x)) # 取小数部分

tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor([[4., 4., 4.],
        [4., 4., 4.]])
tensor([[3., 3., 4.],
        [4., 3., 3.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor([[0.4009, 0.4505, 0.6772],
        [0.8545, 0.4672, 0.2331]])


广播机制：张量自动拓展大小
要求：
- 右对齐（某维度相等/其中一个是1）
- 至少有一个维度

In [35]:
a = torch.rand(2,3)
b = torch.rand(3)
c = torch.rand(3,1,1)
print(a)
print(b)
print(c)

tensor([[0.5781, 0.2572, 0.4858],
        [0.6009, 0.7533, 0.6153]])
tensor([0.3697, 0.0189, 0.6317])
tensor([[[0.3812]],

        [[0.6828]],

        [[0.2911]]])


In [38]:
print(a+b)
print(a+c)
print(b+c)

tensor([[0.9478, 0.2761, 1.1176],
        [0.9706, 0.7723, 1.2470]])
tensor([[[0.9593, 0.6384, 0.8670],
         [0.9820, 1.1345, 0.9964]],

        [[1.2609, 0.9400, 1.1687],
         [1.2837, 1.4362, 1.2981]],

        [[0.8692, 0.5483, 0.7770],
         [0.8920, 1.0445, 0.9064]]])
tensor([[[0.7508, 0.4001, 1.0129]],

        [[1.0525, 0.7017, 1.3145]],

        [[0.6608, 0.3100, 0.9229]]])
