# Tensor operations
Yu Jingyao, 1/7/2026

In [1]:
import torch

In [2]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])

In [3]:
# 加法
print(a + b)
print(torch.add(a, b))
print(a.add(b))
# a.add_(b) 原地操作

tensor([[ 6,  8],
        [10, 12]])
tensor([[ 6,  8],
        [10, 12]])
tensor([[ 6,  8],
        [10, 12]])


In [4]:
# 减法
print(a-b)
print(torch.sub(a,b))
print(a.sub(b))
# a.sub_(b)

tensor([[-4, -4],
        [-4, -4]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[-4, -4],
        [-4, -4]])


In [5]:
# 乘法（对应元素直接）
print(a*b)
print(torch.mul(a,b))
print(a.mul(b))
# a.mul_(b)

tensor([[ 5, 12],
        [21, 32]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[ 5, 12],
        [21, 32]])


In [6]:
# 除法（对应元素相除）
print(a / b)
print(torch.div(a,b))
print(a.div(b))
# a.div_(b)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [7]:
# 矩阵乘法
# 二阶矩阵
print(a@b)
print(torch.mm(a,b))
print(a.mm(b))
print(torch.matmul(a,b))
print(a.matmul(b))

# 高阶矩阵（只作用于最后两个维度）
c = torch.ones(2,3,4)
d = torch.ones(4,3)
print(torch.matmul(c,d))


tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor([[[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]])


In [8]:
# 幂运算
print(a**2)
print(torch.pow(a,2))
print(a.pow(2))
print()
# a.pow_(2)

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])



In [9]:
# 开方运算
print(a.sqrt())
# a.sqrt_()

tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])


In [10]:
# 指数运算
print(torch.exp(a))
print(a.exp())
# a.exp_()

# 对数运算
print(torch.log(a)) # 底数为e

tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5981]])
tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5981]])
tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]])


In [11]:
x = torch.rand(2,3) + 3
print(x)

tensor([[3.3275, 3.4721, 3.2105],
        [3.8704, 3.3576, 3.8301]])


In [12]:
# 取整运算
print(torch.floor(x)) # 向下取整
print(x.ceil()) # 向上取整
print(x.round()) # 四舍五入
print(torch.trunc(x)) # 取整数部分
print(torch.frac(x)) # 取小数部分

tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor([[4., 4., 4.],
        [4., 4., 4.]])
tensor([[3., 3., 3.],
        [4., 3., 4.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor([[0.3275, 0.4721, 0.2105],
        [0.8704, 0.3576, 0.8301]])


广播机制：张量自动拓展大小
要求：
- 右对齐（某维度相等/其中一个是1）
- 至少有一个维度

In [13]:
a = torch.rand(2,3)
b = torch.rand(3)
c = torch.rand(3,1,1)
print(a)
print(b)
print(c)

tensor([[0.9809, 0.5785, 0.6528],
        [0.1485, 0.5013, 0.8346]])
tensor([0.5890, 0.6698, 0.0549])
tensor([[[0.4122]],

        [[0.6601]],

        [[0.9925]]])


In [14]:
print(a+b)
print(a+c)
print(b+c)

tensor([[1.5699, 1.2483, 0.7076],
        [0.7376, 1.1711, 0.8895]])
tensor([[[1.3930, 0.9907, 1.0649],
         [0.5607, 0.9135, 1.2468]],

        [[1.6410, 1.2386, 1.3129],
         [0.8087, 1.1614, 1.4948]],

        [[1.9733, 1.5710, 1.6452],
         [1.1410, 1.4938, 1.8271]]])
tensor([[[1.0012, 1.0820, 0.4670]],

        [[1.2491, 1.3299, 0.7150]],

        [[1.5815, 1.6623, 1.0473]]])


比较运算

In [20]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[1,2],[4,3]])
print(torch.eq(a, b)) # 按照元素分别比较,形状不同就会报错
print(torch.equal(a, b)) # 整体比较,只有它是整体比较
print(torch.gt(a, b)) # greater than
print(torch.ge(a, b)) # greater and equal
print(torch.lt(a, b)) # less than
print(torch.le(a, b)) # less and equal
print(torch.ne(a, b)) # not equal

tensor([[ True,  True],
        [False, False]])
False
tensor([[False, False],
        [False,  True]])
tensor([[ True,  True],
        [False,  True]])
tensor([[False, False],
        [ True, False]])
tensor([[ True,  True],
        [ True, False]])
tensor([[False, False],
        [ True,  True]])


排序

In [33]:
c = torch.randint(0,100,(2,3,2))
print(c)
print(torch.sort(c, dim=2).values)
# print(torch.sort(c, descending=True).values) # 降序

tensor([[[48, 35],
         [80, 52],
         [57, 96]],

        [[77, 16],
         [ 2, 35],
         [86, 53]]])
tensor([[[35, 48],
         [52, 80],
         [57, 96]],

        [[16, 77],
         [ 2, 35],
         [53, 86]]])


In [ ]:
# topk
d = torch.randint(0,10,(2,5))
print(d)
print(torch.topk(d, k=2, dim=0))
print(torch.kthvalue(d, k=2, dim=1)) # 第k小的数字
print(torch.kthvalue(d, k=2, dim=0))

tensor([[1, 8, 0, 9, 3],
        [2, 8, 6, 2, 1]])
torch.return_types.topk(
values=tensor([[2, 8, 6, 9, 3],
        [1, 8, 0, 2, 1]]),
indices=tensor([[1, 0, 1, 0, 0],
        [0, 1, 0, 1, 1]]))
torch.return_types.kthvalue(
values=tensor([1, 2]),
indices=tensor([0, 3]))
torch.return_types.kthvalue(
values=tensor([2, 8, 6, 9, 3]),
indices=tensor([1, 1, 1, 0, 0]))
